libs: &libs
- vendor/bower/jquery/jquery.js
- vendor/bower/handlebars/handlebars.js
- vendor/bower/ember/ember.js
- vendor/bower/ember-data/ember-data.js
- vendor/bower/ember-localstorage-adapter/localstorage_adapter.js
app: &app
- app/js/application.js
- app/js/router.js
- app/js/**/*.js
css: &css
- app/css/style.css
all:
- *libs
- *app
- *css
- app/pages/*.html
