vendor: &vendor
- vendor/bower/jquery/jquery.js
- vendor/bower/handlebars/handlebars.js
- vendor/bower/ember/ember.js
- vendor/bower/ember-data/ember-data.js
- vendor/bower/localstorage_adapter/localstorage_adapter.js
libs: &libs
- app/js/application.js
- app/js/router.js
- app/js/**/*.js
css: &css
- app/css/style.css
all:
- *vendor
- *libs
- *css
- app/pages/*.html
